# pylint: disable=invalid-name
# Generated by Django 3.0.4 on 2020-04-27 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20200426_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='answer_explanation',
            field=models.TextField(blank=True, default=''),
        ),
    ]
