# pylint: disable=invalid-name
# Generated by Django 3.0.7 on 2020-10-20 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_news_answer_explanation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='manipulation_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='news.ManipulationCategory'),
        ),
    ]
