# pylint: disable=invalid-name
# Generated by Django 3.0.7 on 2020-12-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20201020_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='source_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='news',
            name='source_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='news',
            name='expected_answer',
            field=models.CharField(choices=[('yes', 'True news'), ('no', 'False news')], max_length=32),
        ),
    ]
