# pylint: disable=invalid-name
# Generated by Django 3.0.7 on 2021-01-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20201221_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='analysis_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
