# pylint: disable=invalid-name
# Generated by Django 3.0.7 on 2021-01-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_news_analysis_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='analysis_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
