# pylint: disable=invalid-name
# Generated by Django 3.0.7 on 2021-05-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_news_analysis_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='language',
            field=models.CharField(
                choices=[('pl', 'Polish'), ('en', 'English')],
                default='pl',
                max_length=2,
            ),
        ),
    ]
